name: CI 
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |pipeline {
    agent Any

    stages {
        stage('Build') {
            steps {
                echo "Building.."
                Bat 'C:\programme\maven\bin/mvn -f https://www.code.dtf.lighting.com/projects/CTX/repos/iac_parent/browse/pom.xml clean install'
                sh 'cp $Module/$Application/target/*.jar $Source'
            }
        }
        stage('Test_Deploy') {
            steps {
                echo "Deploying to Test environment.."
                sh '/programme/scripts/tc_deploy.sh $Server $Application $Source'
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
            }
        }
        stage('input') {
             steps {
                echo "Enter the input"
                timeout(time: 5, unit: "MINUTES") {
                input message: 'Do you want to proceed the deploy in stage?', ok: 'Yes'
              }
              }
              }
stage('Copying'{
            steps {
                echo "Copying artifacts to tomcat servers"
                sh 'scp -i /home/ec2-user/Firstvpc.pem $Module/$Application/target/*.jar ec2-user@13.232.4.54:$Source/'
            }
            }
  stage('Stage_Deploy_Deploy') {
            steps {
                echo "Deploying to Stage Environment.."
                sh '/programme/scripts/tc_deploy.sh $Server $Application $Source'     
 }

    }
}
}

        
